//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diyetDanisanTakipSisFormluOlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danisan
    {
        public int danisan_id { get; set; }
        public string Ad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<bool> Cinsiyet { get; set; }
        public string Telefon { get; set; }
        public Nullable<double> Boy { get; set; }
        public Nullable<double> Kilo { get; set; }
    }
}
