//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diyetDanisanTakipSisFormluOlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diyetisyen
    {
        public int Diyetisyen_id { get; set; }
        public string diyetisyen_adSoyad { get; set; }
        public string password { get; set; }
        public string mail { get; set; }
        public string Telefon { get; set; }
        public string user_name { get; set; }
        public Nullable<bool> Cinsiyet { get; set; }
    }
}
