//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diyetDanisanTakipSisFormluOlan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        public int Randevu_id { get; set; }
        public string randevu_dabisanId { get; set; }
        public Nullable<System.DateTime> randevu_tarih { get; set; }
        public Nullable<int> diyetisyenId { get; set; }
    }
}
